### ISSUE TITLE
Reference bug according in some browsers

### ISSUE THREAD

**Issue by N2123575** [CraftingGamerTom/bstable#14]
On Firefox 68.8.0esr the reference to actionsColumnHTML will not intrepret like expected and will considered as "", so now actions will added

**Comment by CraftingGamerTom** [comment]
@N2123575 What happen? Why was this removed?

Can you provide an example of it not working? I'd like to better understand it to make sure it gets fixed for others

**Comment by CraftingGamerTom** [comment]
#13

**Comment by CraftingGamerTom** [comment]
@N2123575 
It is bad version control and tracking practice to remove information about a bug even if you determine it to be a non-issue. Is this a non-issue?
